Merge Trade dev into master (#406)
* Began re-merge of new trade into old trade script
Minor tweaks to political mapmode
Rolled back economic enhancement localisation to pre static-trade version
KNOWN ISSUE: New trade deal localisation needs to be readded

* Fixed errors due to invalid global price svars
Global price vars will be superceded entirely once the new price system is merged into old trade, but first the system needs to be speed-tested and optimised.

* Enhanced diagnostic capabilities for debug_trade.1

* Fixed loc error not displaying tradegoods offered
WiP fix for Error: change_variable effect [ Variable not of the 'value' scope type. Type: empty ]SELL_declare_internal_available line: 19

* Added better diagnostics for debug_trade.2

* Added preserved non-diagnostic debug_trade.2

* Added performance test events for set_variable scripted effects

* Removed whitespaces after value assignments in se_TRADE
Added performance debug events for poorly-performing se_TRADE effects

* Optimised trade by setting variables ad-hoc rather than at the beginning of trade phase

* WiP migration of demand and price svalues into more maintainable scripted effects
Removed posteffects for more consistent map viewing experience

* WiP merging of new and old trade systems
Put most of the price calculations into scripted effects instead of svalues
Began putting food demand calculations into new scripted effects that will hook into the stockpile system

* Prevented over-ordering for stockpiles that meet demand (still not reducing stockpiles that are selling correctly)

* Fixed sales not completing
Issue was due to bad order size references and bad local sold cut references

* WiP dynamic per-tradezone pricing
Added functionality to update the price based on local demand and sold tradegoods per tradezone

* Changed SELL_set_TZ_prices to use every_country loop

* Changed price update functions to use total demand in TZ div by supply available on market in TZ

* Altered per-TZ pricing to calculate by using TZ demand divided by TZ production

* Re-instated special mapmodes (custom mapmode script not yet integrated)

* Pricing takes into account available stockpiles
Added EXE version of setup editor

* Fixed bad vegetables reference and bad debug event syntax

* Fixed recursive loop in TRADE_clear_local_revenue_cut_flags

* Resolved recursive issues and bad references in purchase transfer and tradezone ranking functions

* Added international trade functionality to PURCHASE script

* Changed scope of external purchase order to governorship owner for iterating list of trade partners

* Added tradezone ranking in seller scope during external purchase orders

* Fixed governorships selecting supplier tradezones outside of their internal trade scope
Changed the scope of tradezone scoring from tradezone to governorship, so that scoring is not persistent between countries while iterating all countries. This would cause unavailable tradezones to be selected by governorships based on scores given by previous countries in every_country.

* Fixed bad scoping in internal tradezone ranking and crash from debug event call

* Added debug log call for external purchase order
Changed scope for external purchase order

* Enabled PURCHASE_order_external to fire.
Ongoing issue:
Script system error!
  Error: Event target link 'scope' returned an unset scope
  Script location: file:  file:  file:  file:  file: events/DEBUG/debug_trade.txt line: 480; PURCHASE_make_internal_shopping_list line: 174; PURCHASE_check_shopping_internal line: 52; PURCHASE_order_external line: 31; PURCHASE_try_supplier line: 177

* External trade now functional
Fixed bad scoping when ranking of tradezones is called by PURCHASE_order_external

* Fixed sales not completing in federal customs union countries
This was due to a bad scope limit in every_governorships that was EXCLUDING those in federations, when it was meant to fire for federations

* Improved historicity of Germany
Changed province borders, 3 new provinces, 2 new tags
Added county government rank

* Added limit to PURCHASE_check_shopping_external to run only once
Added SXH to German Confederation

* Removed some debug_logs from se_PURCHASE, caught error in SELL_set_TZ_prices trigger

* Minor trade GUI reformatting

* Major trade iteration optimisation
Added a limit to SELL_set_TZ_prices every_country loop that restricts looping for countries outside of the relevant tradezones.

* Reorganised SELL_set_TZ_prices to run in every_country, but still getting trade_center not set errors in governorships

* Fixed bad scope in TRADE_count_country_TZs

* Fixed countries outside of federal CUs not trading but still issues finding trade center variables

* Updated province setup, areas and names

* Fixed all trade functionality
Main issue was debug_trade.1 calling the wrong script effects, which was failing to set up the stage for debug_trade.2 to run trade calculations
Also added missing vegetables svalues

* Prevented countries without trade partners from making external purchase orders

* Minor trade optimisations

* Added in-between shipping route calculations to trade transfers

* Added more trade routes

* Created customs unions with Spain for Spanish colonies

* Added WiP list of major natural harbours
Added map of predefined trade bonuses
Fixed some bad change_global_variable calls in PURCHASE_update_shipping

* Added port definition to Livorno